apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: customer-secret
  namespace: wsi
spec:
  refreshInterval: 24m
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: customer-credentials
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_USER
      remoteRef:
        key: customer
        property: username
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: customer
        property: password
    - secretKey: MYSQL_HOST
      remoteRef:
        key: customer
        property: host
    - secretKey: MYSQL_PORT
      remoteRef:
        key: customer
        property: port
    - secretKey: MYSQL_DBNAME
      remoteRef:
        key: customer
        property: dbname
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: product-secret
  namespace: wsi
spec:
  refreshInterval: 24m
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: product-credentials
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_USER
      remoteRef:
        key: product
        property: username
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: product
        property: password
    - secretKey: MYSQL_HOST
      remoteRef:
        key: product
        property: host
    - secretKey: MYSQL_PORT
      remoteRef:
        key: product
        property: port
    - secretKey: MYSQL_DBNAME
      remoteRef:
        key: product
        property: dbname
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order-secret
  namespace: wsi
spec:
  refreshInterval: 24m
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: order-credentials
    creationPolicy: Owner
  data:
    - secretKey: REGION
      remoteRef:
        key: order
        property: aws_region